version: '3'
services:
  lab3-mysql:
    restart: always
    container_name: lab3-mysql
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./src/main/resources/data:/docker-entrypoint-initdb.d
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Fredikfs123456
    ports:
      - 3306:3306
  lab6-spring:
    restart: on-failure
    build: ./
    expose:
      - "10222"
    ports:
      - 10222:10222
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - lab3-mysql

volumes:
  database:
